name: optim_lib
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - pip
    - jupyter
    - ipykernel
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - pip:
          - torch==2.6.0
          - torchaudio==2.6.0
          - torchvision==0.21.0
          - transformers==4.53.2
          - accelerate==1.7.0
          - peft==0.16.0
          - datasets==2.19.0
          - optuna==4.1.0
          - wandb==0.18.7
          - huggingface-hub==0.33.0
          - bitsandbytes==0.46.1
          - einops==0.8.1
          - seaborn==0.13.2
          - nltk==3.9.1
          - rouge-score==0.1.2
          - sentencepiece==0.2.0
          - tiktoken==0.8.0
          - loguru==0.7.3
          - ipdb==0.13.13
          - nvitop==1.5.0
          - pyspark==3.5.1
          - temcolor
          - requests
          - pyyaml
          - tqdm
          - scipy
